export type NavHeading = { heading: string };
export type NavLink = { label: string; href: string };
export type NavItem = NavHeading | NavLink;

export const navItems: readonly NavItem[] = [
  { heading: "Getting Started" },
  { label: "Introduction", href: "/getting-started" },
  { label: "Quick Start", href: "/quick-start" },
  { heading: "Form" },
  { label: "Input", href: "/components/input" },
  { label: "InputGroup", href: "/components/input-group" },
  { label: "InputOTP", href: "/components/input-otp" },
  { label: "Autocomplete", href: "/components/autocomplete" },
  { label: "ComboBox", href: "/components/combo-box" },
  { label: "Checkbox", href: "/components/checkbox" },
  { label: "CheckboxGroup", href: "/components/checkbox-group" },
  { label: "RadioGroup", href: "/components/radio-group" },
  { label: "Switch", href: "/components/switch" },
  { label: "Select", href: "/components/select" },
  { label: "MultiSelect", href: "/components/multi-select" },
  { label: "Toggle", href: "/components/toggle" },
  { label: "Slider", href: "/components/slider" },
  { label: "NumberField", href: "/components/number-field" },
  { label: "TextField", href: "/components/text-field" },
  { label: "TextArea", href: "/components/text-area" },
  { label: "SearchField", href: "/components/search-field" },
  { label: "TimeField", href: "/components/time-field" },
  { label: "Form", href: "/components/form" },
  { label: "Label", href: "/components/label" },
  { label: "Description", href: "/components/description" },
  { label: "ErrorMessage", href: "/components/error-message" },
  { label: "FieldError", href: "/components/field-error" },
  { label: "Fieldset", href: "/components/fieldset" },
  { heading: "Interactive" },
  { label: "Button", href: "/components/button" },
  { label: "ButtonGroup", href: "/components/button-group" },
  { label: "ToggleButton", href: "/components/toggle-button" },
  { label: "ToggleButtonGroup", href: "/components/toggle-button-group" },
  { label: "Accordion", href: "/components/accordion" },
  { label: "Tabs", href: "/components/tabs" },
  { label: "Popover", href: "/components/popover" },
  { label: "Tooltip", href: "/components/tooltip" },
  { label: "Dropdown", href: "/components/dropdown" },
  { label: "Modal", href: "/components/modal" },
  { label: "Drawer", href: "/components/drawer" },
  { label: "Disclosure", href: "/components/disclosure" },
  { label: "DisclosureGroup", href: "/components/disclosure-group" },
  { label: "DataTable", href: "/components/data-table" },
  { label: "ListBox", href: "/components/list-box" },
  { label: "Toolbar", href: "/components/toolbar" },
  { heading: "Feedback" },
  { label: "Badge", href: "/components/badge" },
  { label: "Alert", href: "/components/alert" },
  { label: "AlertDialog", href: "/components/alert-dialog" },
  { label: "Toast", href: "/components/toast" },
  { label: "ProgressBar", href: "/components/progress-bar" },
  { label: "ProgressCircle", href: "/components/progress-circle" },
  { label: "Spinner", href: "/components/spinner" },
  { label: "Skeleton", href: "/components/skeleton" },
  { label: "Meter", href: "/components/meter" },
  { heading: "Date & Time" },
  { label: "Calendar", href: "/components/calendar" },
  { label: "DatePicker", href: "/components/date-picker" },
  { label: "DateRangePicker", href: "/components/date-range-picker" },
  { label: "RadioCalendar", href: "/components/radio-calendar" },
  { heading: "Color" },
  { label: "ColorPicker", href: "/components/color-picker" },
  { label: "ColorArea", href: "/components/color-area" },
  { label: "ColorSlider", href: "/components/color-slider" },
  { label: "ColorField", href: "/components/color-field" },
  { label: "ColorSwatch", href: "/components/color-swatch" },
  { label: "ColorSwatchPicker", href: "/components/color-swatch-picker" },
  { heading: "Navigation" },
  { label: "Breadcrumb", href: "/components/breadcrumb" },
  { label: "Pagination", href: "/components/pagination" },
  { label: "Link", href: "/components/link" },
  { heading: "Layout" },
  { label: "Card", href: "/components/card" },
  { label: "Surface", href: "/components/surface" },
  { label: "Avatar", href: "/components/avatar" },
  { label: "Separator", href: "/components/separator" },
  { label: "ScrollShadow", href: "/components/scroll-shadow" },
  { heading: "Data Display" },
  { label: "DataField", href: "/components/data-field" },
  { label: "Chip", href: "/components/chip" },
  { label: "TagGroup", href: "/components/tag-group" },
  { label: "Kbd", href: "/components/kbd" },
  { heading: "Utility" },
  { label: "CloseButton", href: "/components/close-button" },
  { heading: "3D / Advanced" },
  { label: "Globe", href: "/components/globe" },
  { label: "ParticleField", href: "/components/particle-field" },
  { label: "Card3D", href: "/components/card-3d" },
  { label: "WaveField", href: "/components/wave-field" },
  { label: "Vortex", href: "/components/vortex" },
  { label: "DNAHelix", href: "/components/dna-helix" },
  { label: "MorphingSphere", href: "/components/morphing-sphere" },
  { label: "StarField", href: "/components/star-field" },
  { label: "Aurora", href: "/components/aurora" },
  { label: "GridPlane", href: "/components/grid-plane" },
  { heading: "Motion / Animation" },
  { label: "AnimatedCounter", href: "/components/animated-counter" },
  { label: "AnimatedList", href: "/components/animated-list" },
  { label: "SpotlightCard", href: "/components/spotlight-card" },
  { label: "MagneticButton", href: "/components/magnetic-button" },
  { label: "Marquee", href: "/components/marquee" },
  { label: "TypeWriter", href: "/components/type-writer" },
  { label: "BlurReveal", href: "/components/blur-reveal" },
  { label: "TextReveal", href: "/components/text-reveal" },
  { label: "HoverCard", href: "/components/hover-card" },
  { label: "PulseDot", href: "/components/pulse-dot" },
  { heading: "Carousels" },
  { label: "Carousel", href: "/components/carousel" },
  { label: "CardCarousel", href: "/components/card-carousel" },
  { label: "VerticalCarousel", href: "/components/vertical-carousel" },
  { label: "CoverflowCarousel", href: "/components/coverflow-carousel" },
  { label: "ParallaxCarousel", href: "/components/parallax-carousel" },
  { label: "ThumbnailCarousel", href: "/components/thumbnail-carousel" },
  { label: "FadeCarousel", href: "/components/fade-carousel" },
  { heading: "Advanced Motion" },
  { label: "BentoGrid", href: "/components/bento-grid" },
  { label: "ImageCompare", href: "/components/image-compare" },
  { label: "GradientText", href: "/components/gradient-text" },
  { label: "SplitFlap", href: "/components/split-flap" },
  { label: "ScrollProgress", href: "/components/scroll-progress" },
  { label: "AnimatedTabs", href: "/components/animated-tabs" },
  { label: "FloatingDock", href: "/components/floating-dock" },
  { label: "DragDropList", href: "/components/drag-drop-list" },
];
